# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Crosswalk-DublinCore
version:      0.01
version_from: lib/MARC/Crosswalk/DublinCore.pm
installdirs:  site
requires:
    DublinCore::Record:            0
    MARC::Record:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
